### ISSUE TITLE
Can not solve the problem of scaling 8 times

### ISSUE THREAD

**Issue by sbera7** [AarohiSingla/SRGAN_CustomDataset#5]
The code running fine for scaling 4 times. But when I changed it to 8 times it is giving error.

**Comment by Yago-145** [comment]
Hi! @sbera7 

I'm facing troubles while training, when I execute the main.py file it does nothing, did you do something special??
I followed all the same steps that were specified in the repo to create de environment and install the libraries.
I also tried to execute in colab on a A100 env and in local with my RTX 3070 Ti, but nothing, it does nothing.

Also prepared the dataset in the correct way, with the same dimensions as Aarohi in the YT video of the SRGAN.

Did you do something special to run the code??

**Comment by sbera7** [comment]
Hi @Yago-145,

I am unable to understand the issue you are facing. However, you can try implementing the SRGAN architecture using a different [repository](https://github.com/aladdinpersson/Machine-Learning-Collection/tree/master/ML/Pytorch/GANs/SRGAN), which is what I did. Additionally, you can find a tutorial for it on [YouTube](https://youtu.be/7FO9qDOhRCc?si=sJGGZenW2b20j6L0).

**Comment by Yago-145** [comment]
Thank you so much! @sbera7
